// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvetch/api/v1/api.proto

package apiv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetValuesRequest struct {
	Messages             []*KeyValue        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TtlDuration          *duration.Duration `protobuf:"bytes,2,opt,name=ttl_duration,json=ttlDuration,proto3" json:"ttl_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SetValuesRequest) Reset()         { *m = SetValuesRequest{} }
func (m *SetValuesRequest) String() string { return proto.CompactTextString(m) }
func (*SetValuesRequest) ProtoMessage()    {}
func (*SetValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_261ca598fa2afdd5, []int{0}
}

func (m *SetValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValuesRequest.Unmarshal(m, b)
}
func (m *SetValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValuesRequest.Marshal(b, m, deterministic)
}
func (m *SetValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValuesRequest.Merge(m, src)
}
func (m *SetValuesRequest) XXX_Size() int {
	return xxx_messageInfo_SetValuesRequest.Size(m)
}
func (m *SetValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetValuesRequest proto.InternalMessageInfo

func (m *SetValuesRequest) GetMessages() []*KeyValue {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *SetValuesRequest) GetTtlDuration() *duration.Duration {
	if m != nil {
		return m.TtlDuration
	}
	return nil
}

type SetValuesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValuesResponse) Reset()         { *m = SetValuesResponse{} }
func (m *SetValuesResponse) String() string { return proto.CompactTextString(m) }
func (*SetValuesResponse) ProtoMessage()    {}
func (*SetValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_261ca598fa2afdd5, []int{1}
}

func (m *SetValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValuesResponse.Unmarshal(m, b)
}
func (m *SetValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValuesResponse.Marshal(b, m, deterministic)
}
func (m *SetValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValuesResponse.Merge(m, src)
}
func (m *SetValuesResponse) XXX_Size() int {
	return xxx_messageInfo_SetValuesResponse.Size(m)
}
func (m *SetValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetValuesResponse proto.InternalMessageInfo

type GetValuesRequest struct {
	Requests             []*GetValuesRequest_GetValue `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetValuesRequest) Reset()         { *m = GetValuesRequest{} }
func (m *GetValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetValuesRequest) ProtoMessage()    {}
func (*GetValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_261ca598fa2afdd5, []int{2}
}

func (m *GetValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValuesRequest.Unmarshal(m, b)
}
func (m *GetValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValuesRequest.Marshal(b, m, deterministic)
}
func (m *GetValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValuesRequest.Merge(m, src)
}
func (m *GetValuesRequest) XXX_Size() int {
	return xxx_messageInfo_GetValuesRequest.Size(m)
}
func (m *GetValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValuesRequest proto.InternalMessageInfo

func (m *GetValuesRequest) GetRequests() []*GetValuesRequest_GetValue {
	if m != nil {
		return m.Requests
	}
	return nil
}

// GetValue is a get value request.
type GetValuesRequest_GetValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IsPrefix             bool     `protobuf:"varint,2,opt,name=is_prefix,json=isPrefix,proto3" json:"is_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValuesRequest_GetValue) Reset()         { *m = GetValuesRequest_GetValue{} }
func (m *GetValuesRequest_GetValue) String() string { return proto.CompactTextString(m) }
func (*GetValuesRequest_GetValue) ProtoMessage()    {}
func (*GetValuesRequest_GetValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_261ca598fa2afdd5, []int{2, 0}
}

func (m *GetValuesRequest_GetValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValuesRequest_GetValue.Unmarshal(m, b)
}
func (m *GetValuesRequest_GetValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValuesRequest_GetValue.Marshal(b, m, deterministic)
}
func (m *GetValuesRequest_GetValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValuesRequest_GetValue.Merge(m, src)
}
func (m *GetValuesRequest_GetValue) XXX_Size() int {
	return xxx_messageInfo_GetValuesRequest_GetValue.Size(m)
}
func (m *GetValuesRequest_GetValue) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValuesRequest_GetValue.DiscardUnknown(m)
}

var xxx_messageInfo_GetValuesRequest_GetValue proto.InternalMessageInfo

func (m *GetValuesRequest_GetValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetValuesRequest_GetValue) GetIsPrefix() bool {
	if m != nil {
		return m.IsPrefix
	}
	return false
}

type GetValuesResponse struct {
	Messages             []*KeyValue `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetValuesResponse) Reset()         { *m = GetValuesResponse{} }
func (m *GetValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetValuesResponse) ProtoMessage()    {}
func (*GetValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_261ca598fa2afdd5, []int{3}
}

func (m *GetValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValuesResponse.Unmarshal(m, b)
}
func (m *GetValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValuesResponse.Marshal(b, m, deterministic)
}
func (m *GetValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValuesResponse.Merge(m, src)
}
func (m *GetValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetValuesResponse.Size(m)
}
func (m *GetValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValuesResponse proto.InternalMessageInfo

func (m *GetValuesResponse) GetMessages() []*KeyValue {
	if m != nil {
		return m.Messages
	}
	return nil
}

type SubscribeRequest struct {
	Prefixes             []string `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_261ca598fa2afdd5, []int{4}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetPrefixes() []string {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

type SubscribeResponse struct {
	Messages             []*KeyValue `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_261ca598fa2afdd5, []int{5}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

func (m *SubscribeResponse) GetMessages() []*KeyValue {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*SetValuesRequest)(nil), "kvetch.api.v1.SetValuesRequest")
	proto.RegisterType((*SetValuesResponse)(nil), "kvetch.api.v1.SetValuesResponse")
	proto.RegisterType((*GetValuesRequest)(nil), "kvetch.api.v1.GetValuesRequest")
	proto.RegisterType((*GetValuesRequest_GetValue)(nil), "kvetch.api.v1.GetValuesRequest.GetValue")
	proto.RegisterType((*GetValuesResponse)(nil), "kvetch.api.v1.GetValuesResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "kvetch.api.v1.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "kvetch.api.v1.SubscribeResponse")
}

func init() {
	proto.RegisterFile("kvetch/api/v1/api.proto", fileDescriptor_261ca598fa2afdd5)
}

var fileDescriptor_261ca598fa2afdd5 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0xca, 0x9b, 0x40,
	0x10, 0xc7, 0xd9, 0x48, 0x8b, 0x4e, 0x1a, 0x30, 0xf6, 0x90, 0xd4, 0xd2, 0x56, 0x3c, 0x79, 0x5a,
	0x6b, 0x72, 0x2a, 0xe4, 0x62, 0x08, 0xd8, 0x12, 0x08, 0x62, 0x20, 0x94, 0x5e, 0x82, 0xa6, 0x9b,
	0x74, 0x89, 0x89, 0xd6, 0x5d, 0xa5, 0x79, 0x80, 0x3e, 0x41, 0xdf, 0xa0, 0xc7, 0xbe, 0x60, 0xaf,
	0x1f, 0x6a, 0x94, 0x64, 0x43, 0xf8, 0xe0, 0xfb, 0x4e, 0x3a, 0xb3, 0xff, 0x99, 0xf9, 0xcd, 0x9f,
	0x81, 0xc1, 0xbe, 0x20, 0x7c, 0xf3, 0xc3, 0x0e, 0x53, 0x6a, 0x17, 0x4e, 0xf9, 0xc1, 0x69, 0x96,
	0xf0, 0x44, 0xeb, 0xd5, 0x0f, 0xb8, 0xcc, 0x14, 0x8e, 0xfe, 0xee, 0x5a, 0xb7, 0x27, 0xa7, 0x75,
	0x11, 0xc6, 0x39, 0xa9, 0xd5, 0xfa, 0xfb, 0x5d, 0x92, 0xec, 0x62, 0x62, 0x57, 0x51, 0x94, 0x6f,
	0xed, 0xef, 0x79, 0x16, 0x72, 0x9a, 0x1c, 0xeb, 0x77, 0xf3, 0x37, 0x02, 0x75, 0x49, 0xf8, 0xaa,
	0x2c, 0x61, 0x01, 0xf9, 0x99, 0x13, 0xc6, 0xb5, 0x31, 0xc8, 0x07, 0xc2, 0x58, 0xb8, 0x23, 0x6c,
	0x88, 0x0c, 0xc9, 0xea, 0x8e, 0x06, 0xf8, 0x6a, 0x2a, 0x9e, 0x93, 0x53, 0x55, 0x12, 0xb4, 0x42,
	0x6d, 0x02, 0xaf, 0x38, 0x8f, 0xd7, 0x4d, 0xff, 0x61, 0xc7, 0x40, 0x56, 0x77, 0xf4, 0x06, 0xd7,
	0x00, 0xb8, 0x01, 0xc0, 0xb3, 0xb3, 0x20, 0xe8, 0x72, 0x1e, 0x37, 0x81, 0xf9, 0x1a, 0xfa, 0x17,
	0x18, 0x2c, 0x4d, 0x8e, 0x8c, 0x98, 0x7f, 0x10, 0xa8, 0x9e, 0x08, 0x37, 0x03, 0x39, 0xab, 0x7f,
	0x1b, 0x38, 0x4b, 0x80, 0x13, 0x4b, 0xda, 0x44, 0xd0, 0x56, 0xea, 0x9f, 0x40, 0x6e, 0xb2, 0x9a,
	0x0a, 0xd2, 0x9e, 0x9c, 0x86, 0xc8, 0x40, 0x96, 0x12, 0x94, 0xbf, 0xda, 0x5b, 0x50, 0x28, 0x5b,
	0xa7, 0x19, 0xd9, 0xd2, 0x5f, 0xd5, 0x22, 0x72, 0x20, 0x53, 0xe6, 0x57, 0xb1, 0xf9, 0x19, 0xfa,
	0x9e, 0x88, 0xfa, 0x24, 0xcb, 0x4c, 0x0c, 0xea, 0x32, 0x8f, 0xd8, 0x26, 0xa3, 0x11, 0x69, 0xd6,
	0xd3, 0x41, 0xae, 0xe7, 0x9e, 0x1b, 0x29, 0x41, 0x1b, 0x97, 0x93, 0x2f, 0xf4, 0xcf, 0x98, 0x3c,
	0xfa, 0x8f, 0x40, 0x72, 0xfd, 0x2f, 0xda, 0x02, 0x94, 0xd6, 0x76, 0xed, 0x83, 0x50, 0x27, 0xde,
	0x85, 0x6e, 0xdc, 0x17, 0x9c, 0x61, 0x16, 0xa0, 0x78, 0x77, 0xfb, 0x79, 0x8f, 0xf5, 0xbb, 0xb5,
	0xd5, 0x07, 0xa5, 0xdd, 0xf8, 0x96, 0x4f, 0xf0, 0xee, 0x96, 0x4f, 0x34, 0xeb, 0x23, 0x9a, 0x4e,
	0xa0, 0xbf, 0x49, 0x0e, 0xd7, 0xc2, 0xa9, 0xec, 0xa6, 0xd4, 0x2f, 0x0f, 0xd4, 0x47, 0xdf, 0x5e,
	0x84, 0x29, 0x2d, 0x9c, 0xbf, 0x1d, 0x69, 0xee, 0x7e, 0xfd, 0xd7, 0xe9, 0xcd, 0x6b, 0xa1, 0x9b,
	0x52, 0xbc, 0x72, 0xa2, 0x97, 0xd5, 0x19, 0x8f, 0x1f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x24, 0x58,
	0x78, 0x6e, 0x9e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// SetValues takes a list of key values and stores them in the datastore and
	// will notify subscribers of changes.
	SetValues(ctx context.Context, in *SetValuesRequest, opts ...grpc.CallOption) (*SetValuesResponse, error)
	// GetValues retrieves a list of key values.
	GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error)
	// Subscribe will subscribe to a key or prefix and return the current value
	// and any changes.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (API_SubscribeClient, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) SetValues(ctx context.Context, in *SetValuesRequest, opts ...grpc.CallOption) (*SetValuesResponse, error) {
	out := new(SetValuesResponse)
	err := c.cc.Invoke(ctx, "/kvetch.api.v1.API/SetValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error) {
	out := new(GetValuesResponse)
	err := c.cc.Invoke(ctx, "/kvetch.api.v1.API/GetValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (API_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/kvetch.api.v1.API/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPISubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type aPISubscribeClient struct {
	grpc.ClientStream
}

func (x *aPISubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// SetValues takes a list of key values and stores them in the datastore and
	// will notify subscribers of changes.
	SetValues(context.Context, *SetValuesRequest) (*SetValuesResponse, error)
	// GetValues retrieves a list of key values.
	GetValues(context.Context, *GetValuesRequest) (*GetValuesResponse, error)
	// Subscribe will subscribe to a key or prefix and return the current value
	// and any changes.
	Subscribe(*SubscribeRequest, API_SubscribeServer) error
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) SetValues(ctx context.Context, req *SetValuesRequest) (*SetValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValues not implemented")
}
func (*UnimplementedAPIServer) GetValues(ctx context.Context, req *GetValuesRequest) (*GetValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValues not implemented")
}
func (*UnimplementedAPIServer) Subscribe(req *SubscribeRequest, srv API_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_SetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvetch.api.v1.API/SetValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SetValues(ctx, req.(*SetValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvetch.api.v1.API/GetValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetValues(ctx, req.(*GetValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Subscribe(m, &aPISubscribeServer{stream})
}

type API_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type aPISubscribeServer struct {
	grpc.ServerStream
}

func (x *aPISubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvetch.api.v1.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetValues",
			Handler:    _API_SetValues_Handler,
		},
		{
			MethodName: "GetValues",
			Handler:    _API_GetValues_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _API_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kvetch/api/v1/api.proto",
}
